# Generated by Django 3.0.5 on 2020-05-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_postimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postimg',
            new_name='image',
        ),
    ]
